import "@/styles/globals.css";

import { GeistSans, GeistMono } from "geist/font";
import { ThemeProvider } from "@/components/theme/provider";

export const metadata = {
  title: "Crosswordfish",
  description: "Play free crossword puzzles... generated by AI!",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`font-sans ${GeistSans.variable} ${GeistMono.variable}`}>
        <ThemeProvider
          enableSystem
          defaultTheme="system"
          attribute="class"
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
