import { TooltipProvider } from "@/components/ui/tooltip";
import { GameProvider } from "../state/context";
import { testGrid1, testClues1 } from "@/___tests___/test-data";

export const metadata = {
  title: "Crosswordfish",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function PlayLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <GameProvider initGrid={testGrid1} clues={testClues1}>
      <TooltipProvider>{children}</TooltipProvider>
    </GameProvider>
  );
}
