import { TooltipProvider } from "@/components/ui/tooltip";
import { GameProvider } from "../state/context";
import { sample3 as samplePuzzle } from "@/___tests___/samples";

export const metadata = {
  title: "Crosswordfish",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function PlayLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <GameProvider initGrid={samplePuzzle.grid} clues={samplePuzzle.clues}>
      <TooltipProvider>{children}</TooltipProvider>
    </GameProvider>
  );
}
