import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata = {
  title: "Crosswordfish",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function PlayLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <TooltipProvider>
      <div className="flex h-screen">{children}</div>
    </TooltipProvider>
  );
}
