import type { Clue } from "@/lib/types";

export const testClues: Clue[] = [
  // ACROSS
  {
    number: 1,
    clue: "Opera highlight",
    row: 0,
    cols: [0, 1, 2, 3],
  },
  {
    number: 5,
    clue: "Spanish Mrs.",
    row: 0,
    cols: [5, 6, 7],
  },
  {
    number: 8,
    clue: "Yin and ___",
    row: 0,
    cols: [9, 10, 11, 12],
  },
  {
    number: 12,
    clue: "Place in a house where one might find a cue or Clue",
    row: 1,
    cols: [0, 1, 2, 3, 4, 5, 6, 7],
  },
  {
    number: 14,
    clue: "Sherlock's sister, per two Netflix films",
    row: 1,
    cols: [9, 10, 11, 12, 13],
  },
  {
    number: 16,
    clue: "Caffe Americano base",
    row: 2,
    cols: [0, 1, 2, 3, 4, 5, 6, 7],
  },
  {
    number: 17,
    clue: "Hale and hearty",
    row: 2,
    cols: [9, 10, 11, 12, 13, 14],
  },
  {
    number: 19,
    clue: "Mil. category",
    row: 3,
    cols: [0, 1, 2],
  },
  {
    number: 20,
    clue: "Many a corporate decision-maker",
    row: 3,
    cols: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
  },
  {
    number: 22,
    clue: '"Finding Nemo" kid who scares the fish',
    row: 4,
    cols: [0, 1, 2, 3, 4],
  },
  {
    number: 24,
    clue: '"My thought is...',
    row: 4,
    cols: [8, 9, 10, 11, 12, 13, 14],
  },
  {
    number: 25,
    clue: "Choir voice below soprano",
    row: 5,
    cols: [0, 1, 2, 3],
  },
  {
    number: 26,
    clue: `Knightley's "Pirates of the Caribbean" role`,
    row: 5,
    cols: [5, 6, 7, 8, 9],
  },
  {
    number: 29,
    clue: '"On my way!" text, maybe',
    row: 5,
    cols: [12, 13, 14],
  },
  {
    number: 30,
    clue: "Black-and-white cookies",
    row: 6,
    cols: [3, 4, 5, 6, 7],
  },
  {
    number: 32,
    clue: "Keyboard sound",
    row: 6,
    cols: [10, 11, 12, 13, 14],
  },
  {
    number: 34,
    clue: "Investor who has shares in a company",
    row: 7,
    cols: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  },
  {
    number: 37,
    clue: "Finish, as cupcakes",
    row: 8,
    cols: [0, 1, 2, 3, 4],
  },
  {
    number: 39,
    clue: "Precise",
    row: 8,
    cols: [7, 8, 9, 10, 11],
  },
  {
    number: 40,
    clue: "NFL official",
    row: 9,
    cols: [0, 1, 2],
  },
  {
    number: 41,
    clue: "Fill in, as a lawn bare spot",
    row: 9,
    cols: [5, 6, 7, 8, 9],
  },
  {
    number: 43,
    clue: "Caustic remark",
    row: 9,
    cols: [11, 12, 13, 14],
  },
  {
    number: 47,
    clue: "Heartburn remedy",
    row: 10,
    cols: [0, 1, 2, 3, 4, 5, 6],
  },
  {
    number: 50,
    clue: "Thigh bone",
    row: 10,
    cols: [10, 11, 12, 13, 14],
  },
  {
    number: 51,
    clue: "Seating chart designation",
    row: 11,
    cols: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
  {
    number: 55,
    clue: "Lagunitas Brewing Co. specialty",
    row: 11,
    cols: [12, 13, 14],
  },
  {
    number: 56,
    clue: `"You're killing me, ___!": line from "The Sandlot"`,
    row: 12,
    cols: [0, 1, 2, 3, 4, 5],
  },
  {
    number: 57,
    clue: "Pet dander, for one",
    row: 12,
    cols: [7, 8, 9, 10, 11, 12, 13, 14],
  },
  {
    number: 59,
    clue: "Top-notch",
    row: 13,
    cols: [1, 2, 3, 4, 5],
  },
  {
    number: 60,
    clue: "Mail that doesn't need an envelope, and where both words of 12-, 20-, 34-, and 51-Across can be found?",
    row: 13,
    cols: [7, 8, 9, 10, 11, 12, 13, 14],
  },
  {
    number: 61,
    clue: "Reduced by",
    row: 14,
    cols: [2, 3, 4, 5],
  },
  {
    number: 62,
    clue: "Sault ___ Marie",
    row: 14,
    cols: [7, 8, 9],
  },
  {
    number: 63,
    clue: "Regarding",
    row: 14,
    cols: [11, 12, 13, 14],
  },

  // DOWN
  {
    number: 1,
    clue: "Guide that can become the outline for a meeting's minutes",
    col: 0,
    rows: [0, 1, 2, 3, 4, 5],
  },
  {
    number: 2,
    clue: "Imp",
    col: 1,
    rows: [0, 1, 2, 3, 4, 5],
  },
  {
    number: 3,
    clue: "Commodity from abroad",
    col: 2,
    rows: [0, 1, 2, 3, 4, 5],
  },
  {
    number: 4,
    clue: "___ Lingus: Irish carrier",
    col: 3,
    rows: [0, 1, 2],
  },
  {
    number: 5,
    clue: "Fair to middling",
    col: 5,
    rows: [0, 1, 2, 3],
  },
  {
    number: 6,
    clue: "Civil rights icon Parks whose actions inspired a bus boycott",
    col: 6,
    rows: [0, 1, 2, 3],
  },
  {
    number: 7,
    clue: "Another name for the Roman god Cupid",
    col: 7,
    rows: [0, 1, 2, 3],
  },
  {
    number: 8,
    clue: "Overly agreeable guy",
    col: 9,
    rows: [0, 1, 2, 3, 4, 5],
  },
  {
    number: 9,
    clue: "Starts a poker pot",
    col: 10,
    rows: [0, 1, 2, 3, 4],
  },
  {
    number: 10,
    clue: "Social standards",
    col: 11,
    rows: [0, 1, 2, 3, 4],
  },
  {
    number: 11,
    clue: "Spherical",
    col: 12,
    rows: [0, 1, 2, 3, 4, 5, 6, 7],
  },
  {
    number: 13,
    clue: "Singer McEntire",
    col: 4,
    rows: [1, 2, 3, 4],
  },
  {
    number: 15,
    clue: "Lacking vigor",
    col: 13,
    rows: [1, 2, 3, 4, 5, 6],
  },
  {
    number: 18,
    clue: "One from Athens",
    col: 14,
    rows: [2, 3, 4, 5, 6],
  },
  {
    number: 21,
    clue: "Ruckus",
    col: 8,
    rows: [3, 4, 5],
  },
  {
    number: 23,
    clue: "Plunders",
    col: 3,
    rows: [4, 5, 6, 7, 8],
  },
  {
    number: 26,
    clue: "Brief moment",
    col: 5,
    rows: [5, 6, 7],
  },
  {
    number: 27,
    clue: "Round-bottomed cookware",
    col: 6,
    rows: [5, 6, 7],
  },
  {
    number: 28,
    clue: "Fireplace leftovers",
    col: 7,
    rows: [5, 6, 7, 8, 9],
  },
  {
    number: 31,
    clue: "Wither away",
    col: 4,
    rows: [6, 7, 8],
  },
  {
    number: 32,
    clue: "Public health agcy.",
    col: 10,
    rows: [6, 7, 8],
  },
  {
    number: 33,
    clue: "Leave alone",
    col: 11,
    rows: [6, 7, 8, 9, 10],
  },
  {
    number: 34,
    clue: "Jocelyn Alo's sport",
    col: 2,
    rows: [7, 8, 9, 10, 11, 12, 13, 14],
  },
  {
    number: 35,
    clue: "Good Grips gadget brand",
    col: 8,
    rows: [7, 8, 9],
  },
  {
    number: 36,
    clue: "Little guy",
    col: 9,
    rows: [7, 8, 9],
  },
  {
    number: 37,
    clue: "Counterparts of sororities, for short",
    col: 0,
    rows: [8, 9, 10, 11, 12],
  },
  {
    number: 38,
    clue: "Menu option in a file manager",
    col: 1,
    rows: [8, 9, 10, 11, 12, 13],
  },
  {
    number: 41,
    clue: "Runs water over",
    col: 5,
    rows: [9, 10, 11, 12, 13, 14],
  },
  {
    number: 42,
    clue: "School URL part",
    col: 6,
    rows: [9, 10, 11],
  },
  {
    number: 44,
    clue: "Companeras",
    col: 12,
    rows: [9, 10, 11, 12, 13, 14],
  },
  {
    number: 45,
    clue: `Stewie's teddy bear on "Family Guy"`,
    col: 13,
    rows: [9, 10, 11, 12, 13, 14],
  },
  {
    number: 46,
    clue: 'Marlon of "On the Waterfront"',
    col: 14,
    rows: [9, 10, 11, 12, 13, 14],
  },
  {
    number: 48,
    clue: `"Kate & ___": 1980s sitcom`,
    col: 3,
    rows: [10, 11, 12, 13, 14],
  },
  {
    number: 49,
    clue: `Britons and Gaels`,
    col: 4,
    rows: [10, 11, 12, 13, 14],
  },
  {
    number: 50,
    clue: `Agonize (over)`,
    col: 10,
    rows: [10, 11, 12, 13],
  },
  {
    number: 52,
    clue: `GPS app on iPhones`,
    col: 7,
    rows: [11, 12, 13, 14],
  },
  {
    number: 53,
    clue: `Printer smudge`,
    col: 8,
    rows: [11, 12, 13, 14],
  },
  {
    number: 54,
    clue: `If all ___ fails...`,
    col: 9,
    rows: [11, 12, 13, 14],
  },
  {
    number: 58,
    clue: `Early TV brand`,
    col: 11,
    rows: [12, 13, 14],
  },
];
